version: 2
root-markers:
  - .git/

provide-definition: true

tools:
  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  prettier: &prettier
    format-command: './node_modules/.bin/prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}'

  luafmt: &luafmt
    format-command: 'luafmt --stdin'
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
  lua:
    - <<: *luafmt
  sh:
    - <<: *shellcheck
